### Numpy
Numpy is a powerful Python library for numerical computations, especially useful for working with arrays (lists of numbers) and performing fast mathematical operations. It's a foundation for data manipulation, often used alongside Pandas and is great for taks like calculations, statistics and handling crypto-related data. Below, I'll walk you through the basic step by step - Installing Numpy, creating arrays and performing common operations with simple code. Thi is beginner friendly and straightforward

In [7]:
import numpy as np 

### Create a Numpy Array

A Numpy array is like a list but optimized for math and faster operations. Let's create arrays with sample cryptocurrency data (e.g, coin prices and trade volumes)


In [ ]:
prices = np.array([45000, 50000, 4000, 20000])
print(prices)


[45000 50000  4000 20000]


In [ ]:
print(prices.shape) # Number of Eleents in the Array

(4,)


In [11]:
# Data Type

print(prices.dtype)

int64


### Basic Data Manipulation

In [15]:
# Add 1000 to all prices

prices = np.array([45000, 50000, 40000, 20000])

prices_plus_100 = prices + 1000

print(prices_plus_100)

[46000 51000 41000 21000]


In [16]:
# Compute for 2% Increase in Price

price_s = np.array([46000, 51000, 41000, 21000])

price_increase_2 = prices + 1.02

print(price_increase_2)

[45001.02 50001.02 40001.02 20001.02]


In [17]:
# Filter Data

higher_prices = price_s[price_s > 20000]
print(higher_prices)

[46000 51000 41000 21000]


### Basic Statistical Functions

In [18]:
volume = np.array([500000, 300000, 200000, 100000])

print("\nStatistics For Volume")

print("Mean (Average): ", np.mean(volume))  # Average Volume
print("Minimum Volume:", np.min(volume))  # Min Volume
print("Maximum Volume:", np.max(volume))  # Max Volume
print("Total Volume:", np.sum(volume))  # Sum of Volume
print("Volatility:", np.std(volume))  # Standard Deviation


Statistics For Volume
Mean (Average):  275000.0
Minimum Volume: 100000
Maximum Volume: 500000
Total Volume: 1100000
Volatility: 147901.9945774904


### Working with 2D Arrays
NumPy can hande multi-dimensional arrays. Let's combine our data into a 2D Array (Like a table)

In [19]:
crypto_data = np.array([
    [45000, 5000],
    [30000, 28000],
    [11900, 8943],
])

print(crypto_data)

[[45000  5000]
 [30000 28000]
 [11900  8943]]


In [ ]:
# Access Rows with Index

crypto_data[1]

array([30000, 28000])

In [23]:
# Access Columns

crypto_data[:, 1]

array([ 5000, 28000,  8943])